### ISSUE TITLE
Adding osx-arm64

### ISSUE THREAD

**Issue by mdaeron** [conda-forge/pdftotext-feedstock#27]
### Comment:

Is there a way to add `osx-arm64` support?

**Comment by jan-janssen** [comment]
I created a pull request to trigger the automate migration https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4476 . Once it is merged we can see if `pdftotext` is compatible to `osx-arm64`.

**Comment by jan-janssen** [comment]
It seem `pdftotext` is already working on `osx-arm64` https://github.com/jalan/pdftotext/issues/98 and https://github.com/jalan/pdftotext/pull/86

**Comment by mdaeron** [comment]
> It seem `pdftotext` is already working on `osx-arm64` [jalan/pdftotext#98](https://github.com/jalan/pdftotext/issues/98) and [jalan/pdftotext#86](https://github.com/jalan/pdftotext/pull/86)

As far as I understand, `pdftotext` works on M1 when installed using `brew`. What I'm after is to install it using `conda` or `mamba`, because in my experience mixing `brew` and `conda` (especially in environments) rarely ends well. See also [jalan/pdftotext#113](https://github.com/jalan/pdftotext/issues/113).

**Comment by mdaeron** [comment]
> I created a pull request to trigger the automate migration [conda-forge/conda-forge-pinning-feedstock#4476](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4476) . Once it is merged we can see if `pdftotext` is compatible to `osx-arm64`.

Thanks! Looking forward to testing `pdftotext`.

**Comment by jan-janssen** [comment]
@mdaeron The tests are successful, once the last ones are finished - still waiting for the windows tests - the pull request is merged, this issue is closed and the package should be available on anaconda.org in approximately 1 hour.

**Comment by mdaeron** [comment]
Wow, much speed, very appreciated! :)

**Comment by jan-janssen** [comment]
@mdaeron Can you test it locally? I recently sold my M1 Mac mini, so I currently do not have a system to validate the build is working on native hardware.

**Comment by mdaeron** [comment]
> @mdaeron Can you test it locally? I recently sold my M1 Mac mini, so I currently do not have a system to validate the build is working on native hardware.

I just did, and it works beautifully. Thanks again and don't hesitate to ping me if you need M1 testing for other packages.

**Comment by jan-janssen** [comment]
Perfect - thanks
